// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzj1TKZDmoETEFR00SsGRVhMMe-My2sU',
    appId: '1:167610246520:web:0776b8845223788762548d',
    messagingSenderId: '167610246520',
    projectId: 'rapidwarn',
    authDomain: 'rapidwarn.firebaseapp.com',
    databaseURL: 'https://rapidwarn-default-rtdb.firebaseio.com',
    storageBucket: 'rapidwarn.firebasestorage.app',
    measurementId: 'G-4B5MFPNJGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjp4sMlXOI6uEJCVVSktBeuSf6O2UifVM',
    appId: '1:167610246520:android:ed55733d6c803bf062548d',
    messagingSenderId: '167610246520',
    projectId: 'rapidwarn',
    databaseURL: 'https://rapidwarn-default-rtdb.firebaseio.com',
    storageBucket: 'rapidwarn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrSQD4Ls5Vxh7CI9VR-WFm1L_Tu5oWLiw',
    appId: '1:167610246520:ios:24b6ab52a4cfb80362548d',
    messagingSenderId: '167610246520',
    projectId: 'rapidwarn',
    databaseURL: 'https://rapidwarn-default-rtdb.firebaseio.com',
    storageBucket: 'rapidwarn.firebasestorage.app',
    androidClientId: '167610246520-468he1eq45s8e06k5bpa0kk7kse27ic2.apps.googleusercontent.com',
    iosClientId: '167610246520-22dnqlndh2o4oaqkdp7mukmmr4qs27sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rapidwarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrSQD4Ls5Vxh7CI9VR-WFm1L_Tu5oWLiw',
    appId: '1:167610246520:ios:24b6ab52a4cfb80362548d',
    messagingSenderId: '167610246520',
    projectId: 'rapidwarn',
    databaseURL: 'https://rapidwarn-default-rtdb.firebaseio.com',
    storageBucket: 'rapidwarn.firebasestorage.app',
    androidClientId: '167610246520-468he1eq45s8e06k5bpa0kk7kse27ic2.apps.googleusercontent.com',
    iosClientId: '167610246520-22dnqlndh2o4oaqkdp7mukmmr4qs27sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rapidwarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZzj1TKZDmoETEFR00SsGRVhMMe-My2sU',
    appId: '1:167610246520:web:00392a7df6ee99c762548d',
    messagingSenderId: '167610246520',
    projectId: 'rapidwarn',
    authDomain: 'rapidwarn.firebaseapp.com',
    databaseURL: 'https://rapidwarn-default-rtdb.firebaseio.com',
    storageBucket: 'rapidwarn.firebasestorage.app',
    measurementId: 'G-BSH3TX4H78',
  );

}